# Generated by Django 5.2.12 on 2026-03-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cor',
            table='cor',
        ),
    ]
