# Generated by Django 5.2.12 on 2026-03-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cor_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name': 'cor', 'verbose_name_plural': 'cores'},
        ),
        migrations.AlterModelTable(
            name='cor',
            table=None,
        ),
    ]
