# Generated by Django 5.2.12 on 2026-03-24 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='acessorios',
            field=models.ManyToManyField(blank=True, related_name='veiculos', to='core.acessorio'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='core.cor'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='core.modelo'),
        ),
    ]
