# Generated by Django 5.2.12 on 2026-03-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_veiculo_acessorios_veiculo_cor_veiculo_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='model',
            new_name='modelo',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='nome',
        ),
    ]
